services:
  server-1:
    build:
      context: .
    ports:
      - 80:8000
    container_name: picture_server-server-prod
  
  server-2:
    build:
      context: .
    ports:
      - 8000:8000
    container_name: picture_server-server-test
